local Helpers = dofile(HARNESS_DIR .. "/helpers.lua")
local LocalTime = Helpers.LocalTime

describe("Stats calendar", function()
	it("converts dates to day numbers and back", function()
		local _, ns = Harness.Load()
		local Stats = ns.Stats
		expect(Stats.DayNumber(1970, 1, 1)).toBe(0)
		expect(Stats.DayNumber(2000, 3, 1)).toBe(11017)
		expect(Stats.DayNumber(2024, 2, 29) + 1).toBe(Stats.DayNumber(2024, 3, 1))
		expect(Stats.DayNumber(2100, 2, 28) + 1).toBe(Stats.DayNumber(2100, 3, 1))
		for day = -1000, 30000, 7 do
			local year, month, dayOfMonth = Stats.DateOf(day)
			expect(Stats.DayNumber(year, month, dayOfMonth)).toBe(day)
		end
	end)

	it("knows weekdays", function()
		local _, ns = Harness.Load()
		expect(ns.Stats.Weekday(ns.Stats.DayNumber(1970, 1, 1))).toBe(5) -- Thursday
		expect(ns.Stats.Weekday(ns.Stats.DayNumber(2026, 10, 6))).toBe(3) -- Tuesday
	end)

	it("finds local midnight, also across daylight saving changes", function()
		local _, ns = Harness.Load()
		for _, date in ipairs({ { 2026, 3, 8 }, { 2026, 3, 9 }, { 2026, 11, 1 }, { 2026, 11, 2 } }) do
			local day = ns.Stats.DayNumber(date[1], date[2], date[3])
			local midnight = ns.Stats.MidnightOf(day)
			expect(os.date("%H:%M", midnight)).toBe("00:00")
			expect(ns.Stats.DayOf(midnight)).toBe(day)
		end
	end)
end)

describe("Stats heatmap", function()
	it("buckets values by quartiles of the active days", function()
		local _, ns = Harness.Load()
		local thresholds = ns.Stats.Thresholds({ 0, 1, 2, 3, 4, 5, 6, 7, 8 })
		expect(thresholds).toEqual({ 2, 4, 6 })
		expect(ns.Stats.Bucket(0, thresholds)).toBe(0)
		expect(ns.Stats.Bucket(1, thresholds)).toBe(1)
		expect(ns.Stats.Bucket(3, thresholds)).toBe(2)
		expect(ns.Stats.Bucket(5, thresholds)).toBe(3)
		expect(ns.Stats.Bucket(8, thresholds)).toBe(4)
		expect(ns.Stats.Bucket(5, {})).toBe(0)
		local same = ns.Stats.Thresholds({ 7, 7, 7 })
		expect(ns.Stats.Bucket(7, same)).toBe(4)
	end)

	it("totals each day's metric, including the live session", function()
		local now = LocalTime(2026, 10, 8, 15)
		local world, ns = Harness.Boot({ now = now })
		Helpers.GainMoney(world, 300)
		ns.History.Add(Helpers.Record(ns, { id = 50, startedAt = LocalTime(2026, 10, 7), money = 100, xp = 5 }))
		ns.History.Add(Helpers.Record(ns, { id = 51, startedAt = LocalTime(2026, 10, 7, 20), money = 20, xp = 6 }))
		local gold = ns.Stats.Daily("gold", world.clock.server, true)
		expect(gold[ns.Stats.DayNumber(2026, 10, 7)]).toBe(120)
		expect(gold[ns.Stats.DayNumber(2026, 10, 8)]).toBe(300)
		local time = ns.Stats.Daily("time", world.clock.server, true)
		expect(time[ns.Stats.DayNumber(2026, 10, 7)]).toBe(7200)
	end)
end)

describe("Stats records and streaks", function()
	it("keeps the best sessions and needs 15 active minutes for hourly records", function()
		local now = LocalTime(2026, 10, 8, 15)
		local _, ns = Harness.Boot({ now = now })
		local add = function(fields)
			ns.History.Add(Helpers.Record(ns, fields))
		end
		add({ id = 10, startedAt = LocalTime(2026, 10, 1), duration = 600, money = 900000, kills = 5 })
		add({ id = 11, startedAt = LocalTime(2026, 10, 2), duration = 3600, money = 100000, kills = 90 })
		add({ id = 12, startedAt = LocalTime(2026, 10, 3), duration = 7200, money = 100000, kills = 90 })
		local records = ns.Stats.Records(now, true)
		expect(records.mostGold.id).toBe(10)
		expect(records.goldPerHour.id).toBe(11)
		expect(records.longest.id).toBe(12)
		expect(records.mostKills.id).toBe(11) -- ties keep the earlier session
	end)

	it("counts current and longest daily streaks", function()
		local now = LocalTime(2026, 10, 8, 15)
		local _, ns = Harness.Load({ now = now })
		ns.Database.Init()
		local function add(id, day)
			ns.History.Add(Helpers.Record(ns, { id = id, startedAt = LocalTime(2026, 9, day) }))
		end
		add(1, 1)
		add(2, 2)
		add(3, 3)
		add(4, 4)
		add(5, 20)
		add(6, 30)
		ns.History.Add(Helpers.Record(ns, { id = 7, startedAt = LocalTime(2026, 10, 1) }))
		ns.History.Add(Helpers.Record(ns, { id = 8, startedAt = LocalTime(2026, 10, 7) }))
		local streaks = ns.Stats.Streaks(now)
		expect(streaks.current).toBe(1) -- played yesterday, not yet today
		expect(streaks.longest).toBe(4)
		ns.History.Add(Helpers.Record(ns, { id = 9, startedAt = LocalTime(2026, 10, 8, 9) }))
		expect(ns.Stats.Streaks(now).current).toBe(2)
		expect(ns.Stats.Streaks(LocalTime(2026, 10, 12)).current).toBe(0)
	end)

	it("averages session length and sessions per week", function()
		local now = LocalTime(2026, 10, 14, 12)
		local _, ns = Harness.Load({ now = now })
		ns.Database.Init()
		ns.History.Add(Helpers.Record(ns, { id = 1, startedAt = LocalTime(2026, 10, 1), duration = 3600 }))
		ns.History.Add(Helpers.Record(ns, { id = 2, startedAt = LocalTime(2026, 10, 8), duration = 1800 }))
		local overview = ns.Stats.Overview(ns.History.Lifetime(), now, true)
		expect(overview.averageSeconds).toBe(2700)
		expect(overview.sessionsPerWeek).toBe(1)
	end)
end)
